#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "ld [TERM...]"
    echo "  Displays all the lines in done.txt file sorted by priority with line"
    echo "  numbers. If TERM specified, lists all lines that contain TERM(s). Hides"
    echo "  all tasks that contain TERM(s) preceded by a minus sign (i.e. -TERM)."
    exit
}

$TODO_SH -f command lf done.txt $#
